### ISSUE TITLE
Plugin detection not working

### ISSUE THREAD

**Issue by azubieta** [TheAssassin/linuxdeploy-plugin-qt#3]
When Qt5 Gui module is used is mandatory to deploy the platform plugins usually contained in:
<qt installation path>/plugins/platforms
those should be deployed in <AppDir>/usr/plugins/platforms/

**Comment by TheAssassin** [comment]
@azubieta please show me a log first. Of course those plugins are deployed when the gui module is detected.

**Comment by TheAssassin** [comment]
See https://github.com/TheAssassin/linuxdeploy-plugin-qt/blob/master/src/main.cpp#L142.

**Comment by azubieta** [comment]
Logs here https://pastebin.com/etyfUqKb
This only happens in my local system, not in travis-ci.
https://travis-ci.org/azubieta/appimage-metadata-extractor/builds/395880498#L3541

**Comment by TheAssassin** [comment]
As you can see, the list of found plugins is empty. Therefore, I changed the title, as this is not a problem with the gui plugin's deployment code, but with the plugin detection.

I've added some really verbose debug logging to the relevant code. Please re-run linuxdeploy with `DEBUG=1` in your environment, and provide the log.
